# Linear Algebra in Deep Learning with Numpy library
This notebook contains basic linear algebra knowledge that will be used in deep learning context. Most of the content comes from [Goodfellow, I. (2016). Deep learning. Chapter 2](https://www.deeplearningbook.org/contents/linear_algebra.html) and combined with corresponding useful numpy packages.

In [2]:
# potential useful packages
import numpy as np

## 1. Scalars, Vectors, Matrices and Tensors

Linear algebra involves three types of mathematical objects:

- **Scalars *a***: A scalar is a single number which is usually written in lowercase italics format. It could be integers, real, natural number, etc. In terms of numpy code, we will have the following representation:

In [3]:
a = 16
b = 1.5

- **Vectors** $\mathbf{x}$: A vector is an array of numbers,represented by lowercase in bold. The element of the vector are written in italic with the same name and a subscript indicating the order. Vectors by default are considered as a column vector with shape $(n,1)$. It can be represented a follows:

$$\mathbf{x} = \begin{bmatrix}x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix}$$

> The first element of $\mathbf{x}$ is $x_1$, the second element is $x_2$ and so on. If each element is in $\mathbb{R}$ and the vector has $n$ elements, then the vector lies in the set formed by taking the Cartesian product of $\mathbb{R}$ n times, denoted as $\mathbb{R}^n$

In [4]:
# Assume that x is a vector of [1,2,3]. Then we can convert it to NumPy array as follows
x = np.array([1,2,3])

# We can check its shape using the following code. Note that (3,) is a 1D dimension. It could be used as (3,1) or (1,3).
x.shape

(3,)

- **Matrices** $\mathbf{A}$: A matrix is a 2-D array of numbers, so each element is identified by two indices instead of just one. It is represented with uppercase name with bold.

$$\mathbf{A} = \begin{bmatrix}A_{1,1} & A_{1,2} \\ A_{2,1} & A_{2,2} \end{bmatrix}$$

> If each element in $\mathbf{A}$ is $\mathbb{R}$ and the matrix has a height of $m$ and a width of $n$, then we say $\mathbf{A} \in \mathbb{R}^{m \times n}$. The element is represented by its name in italics and the subscripts $(i,j)$. $A_{i,j}$ refers to the element located at the ith row and j's column. We can use $A_{i,:}$ to represent the row vector at ith row. And $A_{:,j}$ to represent the column vector at jth column. Besides, $f(\mathbf{A})_{i,j}$ gives element $(i,j)$ of the matrix computed by applying the function $f$ to $\mathbf{A}$

In [7]:
# Assume that x is a 2x2 matrix. Then we can convert it to NumPy array as follows
A = np.array([[1,2],[3,4]])

# We can check its shape using the following code.
A.shape

(2, 2)

- **Tensors** **A**: Tensors refers to araay with more than two axes. For example, the element in three dimension tensors will be denoted as $\mathbf{A}_{i,j,k}$

In [8]:
# Assume that x is a 2x3x4 tensor. Then we can convert it to NumPy array as follows
A = np.random.rand(2,3,4)
print(A)
# We can check its shape using the following code.
A.shape

[[[0.59002823 0.07188662 0.3249033  0.04258052]
  [0.45066696 0.26455611 0.50177915 0.18408177]
  [0.43086988 0.65608907 0.45279997 0.61763061]]

 [[0.66967302 0.03087927 0.39188447 0.4152889 ]
  [0.29840969 0.61133251 0.45948126 0.46662559]
  [0.81499881 0.06608919 0.28045881 0.256501  ]]]


(2, 3, 4)

Next, we will look into **transpose**. The transpose of a matrix is the mirror image of the matrix across a diagonal line, called the **main diagonal**, running down to the right, starting from its upper left corner, represented as $[A_{1,1},A_{2,2}]$ given the matrix below.

$$\mathbf{A} = \begin{bmatrix}A_{1,1} & A_{1,2} \\ A_{2,1} & A_{2,2}\\ A_{3,1} & A_{3,2} \end{bmatrix}$$

The transpose of a matrix $\mathbf{A}$, denoted as $\mathbf{A}^T$.

$$(\mathbf{A}^T)_{i,j} = A_{j,i}$$

Therefore, the transpose matrix of a $(m\times n)$ matrix will be in shape $(n \times m)$
$$\mathbf{A} = \begin{bmatrix}A_{1,1} & A_{1,2} \\ A_{2,1} & A_{2,2}\\ A_{3,1} & A_{3,2} \end{bmatrix}$$
$$\mathbf{A}^T = \begin{bmatrix}A_{1,1} & A_{2,1} & A_{3,1} \\ A_{1,2} & A_{2,2} & A_{3,2} \end{bmatrix}$$

Now, let's apply the transpose to different types of objects in the Numpy library. With the Numpy library, we use the function [transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html). 

In [9]:
# Matrix
a = np.array(1)
a.shape
a.T